### ISSUE TITLE
Not working with CL-174686

### ISSUE THREAD

**Issue by cemtechuk** [AstroFloof/AFSuperNobs#5]

**Comment by Borketh** [comment]
Please provide more detail. Not working in what way?

**Comment by Borketh** [comment]
Note: Ensure you are using SML 3.2.0/3.2.1 at the top of SMM

**Comment by cemtechuk** [comment]
My bad, I had to read the description to realize that I had to use the special detonator for these bombs.
Thanks for replying really quickly. I normally don't write those messages on GH but there was a problem while joining your discord

**Comment by Borketh** [comment]
What's the issue joining the discord?
